ROOT: 'Snakemake'

#dataset_dir: 'processed_data'

#neighbors : [5]
#graph_method: ['umap']
#reps: ['X']
#nns: [True]
#clust_method: ['leiden']
#resolution: [1.2]




DATASETS:
    TabulaMurisHeart_cxg:
      dataset_id: 1fe63353-9e75-4824-aa30-ed8d84be748c
      #download_script: https://datasets.cellxgene.cziscience.com/b6fff8a8-b297-4715-b041-43d23a4e0474.h5ad
      process_script: 
      subdatasets:
      cell_labels: predicted_cell_types
      input_type: other
      normalization:
      batch_labels:
      standard: silver
      organism: mus_musculus
      tissue: heart
    TabulaSapiensLiver_cxg:
      dataset_id: 6d41668c-168c-4500-b06a-4674ccf3e19d
      download_script: https://datasets.cellxgene.cziscience.com/52d623c9-824c-4b62-aed7-f0f7f50858a8.h5ad
      process_script: 
      subdatasets:
      cell_labels: cell_type
      input_type: other
      normalization:
      batch_labels:
      standard: gold
      organism: homo_sapiens
      tissue: liver
    BaronPancreasData:
      download_script: /work/Master_Project/bash_scripts/get_data.R
      process_script: /work/Master_Project/Notebooks/r_datas.py
      subdatasets:
      cell_labels: predicted_cell_type
      input_type: other
      normalization:
      batch_labels:
      standard: silver
      organism: homo_sapiens
      tissue: pancreas
    RomanovBrainData:
      download_script: /work/Master_Project/bash_scripts/get_data.R
      process_script: /work/Master_Project/Notebooks/r_datas.py
      subdatasets:
      cell_labels: predicted_cell_type
      input_type: raw
      normalization:
      batch_labels:
      standard: silver
      organism: mus_musculus
      tissue: brain
    UsoskinBrainData:
      download_script: /work/Master_Project/bash_scripts/package.R
      process_script: /work/Master_Project/Notebooks/r_datas.py
      subdatasets:
      cell_labels: predicted_cell_type
      input_type: raw
      normalization:
      batch_labels:
      standard: silver
      organism: mus_musculus
      tissue: brain
    DarmanisBrainData:
      download_script: /work/Master_Project/bash_scripts/get_data.R
      process_script: /work/Master_Project/Notebooks/r_datas.py
      subdatasets:
      cell_labels: predicted_cell_type
      input_type: raw
      normalization:
      batch_labels:
      standard: silver
      organism: homo_sapiens
      tissue: brain
    SegerstolpePancreasData:
      download_script: /work/Master_Project/bash_scripts/package.R
      process_script: /work/Master_Project/Notebooks/r_datas.py
      subdatasets:
      cell_labels: predicted_cell_type
      input_type: raw
      normalization:
      batch_labels:
      standard: silver
      organism: homo_sapiens
      tissue: pancreas
    TasicBrainData:
      download_script: /work/Master_Project/bash_scripts/package.R
      process_script: /work/Master_Project/Notebooks/r_datas.py
      subdatasets:
      cell_labels: predicted_cell_type
      input_type: raw
      normalization:
      batch_labels:
      standard: silver
      organism: mus_musculus
      tissue: brain
    ZeiselBrainData:
      download_script: /work/Master_Project/bash_scripts/get_data.R
      process_script: /work/Master_Project/Notebooks/r_datas.py
      subdatasets:
      cell_labels: predicted_cell_type
      input_type: raw
      normalization:
      batch_labels:
      standard: silver
      organism: mus_musculus
      tissue: brain
    XinPancreasData:
      download_script: /work/Master_Project/bash_scripts/get_data.R
      process_script: /work/Master_Project/Notebooks/r_datas.py
      subdatasets:
      cell_labels: predicted_cell_type
      input_type: raw
      normalization:
      batch_labels:
      standard: silver
      organism: homo_sapiens
      tissue: pancreas
    XinPancreasData_non_normalized: #correct processing. first version was processed as if counts were raw
      download_script: /work/Master_Project/bash_scripts/get_data.R
      process_script: /work/Master_Project/Notebooks/r_datas.py
      subdatasets:
      cell_labels: predicted_cell_type
      input_type: rpkm
      normalization:
      batch_labels:
      standard: silver
      organism: homo_sapiens
      tissue: pancreas
    TabulaMurisHeart_cxg_raw:   #correct processing. first version was processed as if counts weren't raw (without scaling)
      dataset_id: 1fe63353-9e75-4824-aa30-ed8d84be748c
      #download_script: https://datasets.cellxgene.cziscience.com/b6fff8a8-b297-4715-b041-43d23a4e0474.h5ad
      process_script: 
      subdatasets:
      cell_labels: predicted_cell_types
      input_type: raw
      normalization:
      batch_labels:
      standard: silver
      organism: mus_musculus
      tissue: heart
    Jung:
      subdatasets:
      download_script: /work/Master_Project/bash_scripts/jung.sh
      process_script: /work/Master_Project/Notebooks/jung.py
      path: /work/Master_Project/processed_data/Jung.h5ad
      cell_labels: label
      input_type: raw
      normalization:
      batch_labels:
      standard: gold
      organism: mus_musculus
      tissue: testis
    # sc_Celseq2_5cl_p1:
    #   download_script: /work/Master_Project/bash_scripts/tian.sh
    #   path:  /work/Master_Project/processed_data/sc_Celseq2_5cl_p1.h5ad
    #   cell_labels: cell_line_demuxlet
    #   input_type: raw
    #   normalization:
    #   batch_labels:
    # sc_Celseq2_5cl_p2:
    #   download_script: /work/Master_Project/bash_scripts/tian.sh
    #   path:  /work/Master_Project/processed_data/sc_Celseq2_5cl_p2.h5ad
    #   cell_labels: cell_line_demuxlet
    #   input_type: raw
    #   normalization:
    #   batch_labels:
    # sc_Celseq2_5cl_p3:
    #   download_script: /work/Master_Project/bash_scripts/tian.sh
    #   path:  /work/Master_Project/processed_data/sc_Celseq2_5cl_p3.h5ad
    #   cell_labels: cell_line_demuxlet
    #   input_type: raw
    #   normalization:
    #   batch_labels:
    Tian:
      download_script: /work/Master_Project/bash_scripts/tian.sh
      process_script: /work/Master_Project/Notebooks/tian.py
      subdatasets: [sc_Celseq2_5cl_p3,sc_Celseq2_5cl_p2, sc_Celseq2_5cl_p1, sce_sc_10x_5cl_qc, sce_sc_10x_qc, sce_sc_CELseq2_qc, sce_sc_Dropseq_qc]
      path: 
      cell_labels: cell_line_demuxlet
      input_type: raw
      normalization:
      batch_labels:
      standard: gold
      organism: homo_sapiens
      tissue: lung


    # # sce_sc_10x_5cl_qc:
    # #   path:  /work/Master_Project/processed_data/sce_sc_10x_5cl_qc.h5ad
    # #   labels: cell_line_demuxlet
    # #   input_type: raw
    # #   normalization:
    
    # # sce_sc_10x_qc:
    # #   path:  /work/Master_Project/processed_data/sce_sc_10x_qc.h5ad
    # #   labels: cell_line_demuxlet
    # #   input_type: raw
    # #   normalization:

    # # sce_sc_CELseq2_qc:
    # #   path:  /work/Master_Project/processed_data/sce_sc_CELseq2_qc.h5ad
    # #   labels: cell_line_demuxlet
    # #   input_type: raw
    # #   normalization:
    
    # # sce_sc_Dropseq_qc:
    # #   path:  /work/Master_Project/processed_data/sce_sc_Dropseq_qc.h5ad
    # #   labels: cell_line_demuxlet
    # #   input_type: raw
    # #   normalization:

    Zheng:
      download_script: /work/Master_Project/bash_scripts/zheng.sh
      process_script: /work/Master_Project/Notebooks/zheng.py
      subdatasets:
      input_type: raw
      normalization:
      rep:
      standard: gold
      organism: homo_sapiens
      tissue: blood
      batch_labels:
      cell_labels: label
      
    
    Yan:
      download_script: /work/Master_Project/bash_scripts/yan_2.sh
      process_script: /work/Master_Project/Notebooks/yan.py
      subdatasets:
      cell_labels: cell_labels
      input_type: rpkm
      normalization:
      rep:
      batch_labels:
      standard: gold
      organism: homo_sapiens
      tissue: embryo
    Biase:
      subdatasets:
      download_script: /work/Master_Project/bash_scripts/biase.sh
      process_script: /work/Master_Project/Notebooks/biase.py
      path: /work/Master_Project/processed_data/Biase_fpkm.h5ad
      cell_labels: cell_type
      input_type: fpkm
      normalization:
      rep:
      standard: gold
      organism: mus_musculus
      tissue: embryo
      batch_labels:
    Deng:
      download_script: /work/Master_Project/bash_scripts/deng_check.sh
      process_script: /work/Master_Project/Notebooks/deng.py
      subdatasets: 
      cell_labels: cell_labels
      input_type: raw
      normalization:
      rep:
      batch_labels: #sample
      standard: gold
      organism: mus_musculus
      tissue: embryo
    Kolodziejczyk:
      download_script: /work/Master_Project/bash_scripts/kolodziejczyk.sh
      process_script: /work/Master_Project/Notebooks/kolodziejczyk.py
      subdatasets: 
      cell_labels: cell_labels
      input_type: raw
      normalization:
      rep:
      batch_labels: #batch
      standard: gold
      organism: mus_musculus
      tissue: embryo
    Koh:
      download_script: /work/Master_Project/bash_scripts/koh.sh
      process_script: /work/Master_Project/Notebooks/koh.py
      subdatasets: 
      cell_labels: cell_labels
      input_type: tpm
      normalization:
      rep:
      batch_labels: 
      standard: gold
      organism: mus_musculus
      tissue: embryo stem cells

    Goolam:
      #path: /work/Master_Project/processed_data/Goolam.h5ad
      download_script: /work/Master_Project/bash_scripts/goolam.sh
      process_script: /work/Master_Project/Notebooks/goolam.py
      subdatasets: 
      cell_labels: cell_labels
      input_type: raw
      normalization:
      rep:
      batch_labels: #batch
      standard: gold
      organism: mus_musculus
      tissue: embryo


TRANSFER_LEARNING:
  census_version: "2024-07-01"
  organism: 
    - "mus_musculus"
    - "homo_sapiens"


GRAPH_GENERATION:
  sim_measure:
    - 'phs'
    - 'rho'
    - 'euclidean'
    - 'braycurtis'
    - 'cosine'
    - 'spearman'
    - 'correlation'  #is pearson correlation 

   # - 'manhattan'
  # nns: 
  #   - 'True'
  #   #- 'False'
  neighbors:    #define list with some fixed step 
    start: 3
    end: 100
    step: 1
  graph_method:
   - 'umap'
   - 'gauss'
   - 'jaccard_phenograph'
   - 'jaccard_seurat'

CLUSTERING:
  leiden:
    res:
      start: 0.001
      stop: 2
      step: 0.02
    partition_type:
      - RBConfigurationVertexPartition
      - CPMVertexPartition
      - RBERVertexPartition
  louvain:
    res:
      start: 0.001
      stop: 2
      step: 0.02
    partition_type:
      - RBConfigurationVertexPartition
      - CPMVertexPartition
      - RBERVertexPartition

  

    
